window.ARTIFACT_WORLD = [
  {
    id: "houmuwu-ding",
    name: "后母戊鼎",
    type: "青铜器",
    era: "商代晚期（约公元前 13 世纪）",
    civilization: "中华文明 · 商",
    museum: "中国国家博物馆，北京",
    featured: true,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/HouMuWuDingFullView.jpg/1280px-HouMuWuDingFullView.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/HouMuWuDingFullView.jpg/800px-HouMuWuDingFullView.jpg",
    summary: "已知最重的古代青铜礼器，为商王祭祀母亲而铸。",
    story: "后母戊鼎出土于河南安阳殷墟，器腹内壁铸有“后母戊”三字，是商王为母亲戊所做的祭器。鼎身厚重，耳、腹、足皆饰兽面纹，铸造时需多块陶范合浇。它不只是一件铜器，更是商代王室把孝与权力同时浇进青铜里的证据。"
  },
  {
    id: "sanxingdui-gold-mask",
    name: "三星堆黄金面具",
    type: "金银器",
    era: "商代（约公元前 12–11 世纪）",
    civilization: "古蜀文明",
    museum: "三星堆博物馆，广汉",
    featured: true,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Gold_Mask_%28%E9%BB%84%E9%87%91%E9%9D%A2%E7%BD%A9%29.jpg/1280px-Gold_Mask_%28%E9%BB%84%E9%87%91%E9%9D%A2%E7%BD%A9%29.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Gold_Mask_%28%E9%BB%84%E9%87%91%E9%9D%A2%E7%BD%A9%29.jpg/800px-Gold_Mask_%28%E9%BB%84%E9%87%91%E9%9D%A2%E7%BD%A9%29.jpg",
    summary: "金箔贴在青铜面上，古蜀神祇因此有了一层太阳的皮肤。",
    story: "三星堆出土的黄金面具并非独立金器，而是覆盖在青铜头像上的金箔面。黄金在古蜀与中原同样指向神圣，却长成完全不同的五官：粗眉、尖耳、阔口。祭祀坑里的金杖、金面与青铜神树放在一起，说明长江上游曾有一套自成一体的信仰技术。"
  },
  {
    id: "goujian-sword",
    name: "越王勾践剑",
    type: "青铜器",
    era: "春秋晚期（约公元前 5 世纪）",
    civilization: "中华文明 · 越",
    museum: "湖北省博物馆，武汉",
    featured: false,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/20230208_Bronze_sword_used_by_King_Goujian_of_Yue_01.jpg/1280px-20230208_Bronze_sword_used_by_King_Goujian_of_Yue_01.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/20230208_Bronze_sword_used_by_King_Goujian_of_Yue_01.jpg/800px-20230208_Bronze_sword_used_by_King_Goujian_of_Yue_01.jpg",
    summary: "深埋两千多年仍寒光逼人，剑格上错金铭文自称越王。",
    story: "1965 年，这把剑在湖北江陵望山楚墓出土，出土时仍锋利可裁纸。剑身饰菱形暗纹，近格处有鸟篆铭文“越王勾践 自作用剑”。越国以铸剑闻名，这把剑把卧薪尝胆的传说，收束成一件可以握在手里的青铜事实。"
  },
  {
    id: "siyang-fangzun",
    name: "四羊方尊",
    type: "青铜器",
    era: "商代晚期（约公元前 13–11 世纪）",
    civilization: "中华文明 · 商",
    museum: "中国国家博物馆，北京",
    featured: false,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Fyra_baggars_kvadripod.jpg/1280px-Fyra_baggars_kvadripod.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Fyra_baggars_kvadripod.jpg/800px-Fyra_baggars_kvadripod.jpg",
    summary: "四只卷角羊从尊的四角探出头来，是商代青铜的戏剧高峰。",
    story: "四羊方尊出土于湖南宁乡，器形为方形酒尊，四角各铸一只大角山羊，羊身与器壁浑然一体。肩部还盘绕着龙纹。如此复杂的分铸与合范，说明江南同样掌握着一流的青铜技术，商文化的辐射远比都城殷墟更广。"
  },
  {
    id: "tang-sancai",
    name: "唐三彩马俑",
    type: "陶瓷",
    era: "唐代（8 世纪）",
    civilization: "中华文明 · 唐",
    museum: "各地博物馆藏（河南出土典型器）",
    featured: false,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Dinastia_tang%2C_gruppo_di_figure_in_porcellana_sancai%2C_dalla_provincia_dell%27Henan%2C_inizio_dell%27VIII_sec_03_cavalli_e_palafreniere.jpg/1280px-Dinastia_tang%2C_gruppo_di_figure_in_porcellana_sancai%2C_dalla_provincia_dell%27Henan%2C_inizio_dell%27VIII_sec_03_cavalli_e_palafreniere.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Dinastia_tang%2C_gruppo_di_figure_in_porcellana_sancai%2C_dalla_provincia_dell%27Henan%2C_inizio_dell%27VIII_sec_03_cavalli_e_palafreniere.jpg/800px-Dinastia_tang%2C_gruppo_di_figure_in_porcellana_sancai%2C_dalla_provincia_dell%27Henan%2C_inizio_dell%27VIII_sec_03_cavalli_e_palafreniere.jpg",
    summary: "黄绿白釉流在陶马上，盛唐的出行仪仗被烧进了随葬里。",
    story: "唐三彩并非日常餐具，而是给墓葬准备的明器。河南出土的马俑、牵马俑成组出现，釉色在窑中垂流，形成斑斓的“三彩”。马的体态丰肥，鞍鞯细致，说明长安对西域良马的热爱已经进入阴间编制。看见它们，等于看见一条通往来世的丝绸之路。"
  },
  {
    id: "kangxi-vase",
    name: "清康熙青花五伦图瓶",
    type: "陶瓷",
    era: "清代康熙年间（17–18 世纪）",
    civilization: "中华文明 · 清",
    museum: "大都会艺术博物馆，纽约",
    featured: false,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/%E6%B8%85%E5%BA%B7%E7%86%99_%E6%99%AF%E5%BE%B7%E9%8E%AE%E7%AA%AF%E9%9D%92%E8%8A%B1%E4%BA%94%E5%80%AB%E5%9C%96%E7%85%A8%E7%93%B7%E7%93%B6-Vase_with_auspicious_animals_MET_DP-14359-001.jpg/800px-%E6%B8%85%E5%BA%B7%E7%86%99_%E6%99%AF%E5%BE%B7%E9%8E%AE%E7%AA%AF%E9%9D%92%E8%8A%B1%E4%BA%94%E5%80%AB%E5%9C%96%E7%85%A8%E7%93%B7%E7%93%B6-Vase_with_auspicious_animals_MET_DP-14359-001.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/%E6%B8%85%E5%BA%B7%E7%86%99_%E6%99%AF%E5%BE%B7%E9%8E%AE%E7%AA%AF%E9%9D%92%E8%8A%B1%E4%BA%94%E5%80%AB%E5%9C%96%E7%85%A8%E7%93%B7%E7%93%B6-Vase_with_auspicious_animals_MET_DP-14359-001.jpg/640px-%E6%B8%85%E5%BA%B7%E7%86%99_%E6%99%AF%E5%BE%B7%E9%8E%AE%E7%AA%AF%E9%9D%92%E8%8A%B1%E4%BA%94%E5%80%AB%E5%9C%96%E7%85%A8%E7%93%B7%E7%93%B6-Vase_with_auspicious_animals_MET_DP-14359-001.jpg",
    summary: "钴料画出瑞兽与伦常寓意，景德镇把青花推到了清初的高峰。",
    story: "康熙朝景德镇御窑把进口钴料用得沉稳而层次分明。瓶身瑞兽象征五伦：君臣、父子、夫妇、兄弟、朋友。青花在清代不只是装饰，也是可以摆在厅堂里的道德图解。这件现藏纽约的瓶子，把中国瓷的世界旅行写进了釉下蓝。"
  },
  {
    id: "exekias-cup",
    name: "狄俄尼索斯酒杯",
    type: "陶瓷",
    era: "古希腊古风时期（约公元前 540–530 年）",
    civilization: "古希腊",
    museum: "大英博物馆，伦敦",
    featured: false,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Dionysos_Oinopion_BM_B210.jpg/1280px-Dionysos_Oinopion_BM_B210.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Dionysos_Oinopion_BM_B210.jpg/800px-Dionysos_Oinopion_BM_B210.jpg",
    summary: "酒神躺在船上，葡萄藤从桅杆长到杯沿。",
    story: "陶工埃克塞基亚斯在这只基里克斯杯内壁画下狄俄尼索斯：他斜卧船中，桅杆瞬间长成葡萄藤，海豚绕着船舷跳跃。饮酒的人一低头，就看见神话在酒面下发生。希腊陶瓶把日常宴饮变成可以传阅的史诗插图，这只杯子是其中最温柔的一页。"
  },
  {
    id: "ru-ware",
    name: "汝窑天青釉水仙盆",
    type: "陶瓷",
    era: "北宋（11–12 世纪）",
    civilization: "中华文明 · 宋",
    museum: "国立故宫博物院，台北",
    featured: false,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/%E5%8C%97%E5%AE%8B%E6%B1%9D%E7%AA%AF%E9%9D%92%E7%93%B7%E7%84%A1%E7%B4%8B%E6%B0%B4%E4%BB%99%E7%9B%86_%E5%90%AB%E5%BA%95%E5%BA%A7.tif/lossy-page1-1280px-%E5%8C%97%E5%AE%8B%E6%B1%9D%E7%AA%AF%E9%9D%92%E7%93%B7%E7%84%A1%E7%B4%8B%E6%B0%B4%E4%BB%99%E7%9B%86_%E5%90%AB%E5%BA%95%E5%BA%A7.tif.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/%E5%8C%97%E5%AE%8B%E6%B1%9D%E7%AA%AF%E9%9D%92%E7%93%B7%E7%84%A1%E7%B4%8B%E6%B0%B4%E4%BB%99%E7%9B%86_%E5%90%AB%E5%BA%95%E5%BA%A7.tif/lossy-page1-800px-%E5%8C%97%E5%AE%8B%E6%B1%9D%E7%AA%AF%E9%9D%92%E7%93%B7%E7%84%A1%E7%B4%8B%E6%B0%B4%E4%BB%99%E7%9B%86_%E5%90%AB%E5%BA%95%E5%BA%A7.tif.jpg",
    summary: "雨过天青云破处，宋人把一种天气烧进了釉里。",
    story: "汝窑存世极少，釉色如雨后晴空，开片细如冰裂纹。水仙盆有椭圆口与四云头足，不靠彩绘说话，只靠一层青釉的深浅。宋代宫廷把“克制”本身当成美。看见汝窑，等于看见一种不愿意喧哗的文明选择。"
  },
  {
    id: "terracotta",
    name: "秦始皇陵兵马俑",
    type: "雕塑",
    era: "秦代（公元前 3 世纪）",
    civilization: "中华文明 · 秦",
    museum: "秦始皇帝陵博物院，西安",
    featured: true,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/51714-Terracota-Army.jpg/1280px-51714-Terracota-Army.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/51714-Terracota-Army.jpg/800px-51714-Terracota-Army.jpg",
    summary: "用泥土复制一支帝国军队，让皇帝在地下仍拥有队列。",
    story: "1974 年，临潼农民打井时碰到陶片，一座地下军团被重新看见。陶俑按兵种排列，面容各不相同，原本通体彩绘。它们不是装饰，而是秦始皇陵的守卫编制。泥土被赋予军籍，说明统一中国的那个人，连死后也不愿失去队列。"
  },
  {
    id: "venus-de-milo",
    name: "米洛的维纳斯",
    type: "雕塑",
    era: "希腊化时期（约公元前 130–100 年）",
    civilization: "古希腊",
    museum: "卢浮宫，巴黎",
    featured: true,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Front_views_of_the_Venus_de_Milo.jpg/800px-Front_views_of_the_Venus_de_Milo.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Front_views_of_the_Venus_de_Milo.jpg/640px-Front_views_of_the_Venus_de_Milo.jpg",
    summary: "断臂的爱神，残缺反而成为后世最熟悉的完整。",
    story: "1820 年，这座大理石雕像在爱琴海米洛斯岛被发现。她可能是阿佛洛狄忒，也可能与海神有关；双臂缺失，姿态因此永远开放给想象。卢浮宫把它放在主轴尽端，让每个走近的人先看见身体的扭转，再看见那张平静的脸。残缺在这里不是损失，是邀请。"
  },
  {
    id: "nike",
    name: "萨莫色雷斯的胜利女神",
    type: "雕塑",
    era: "希腊化时期（约公元前 2 世纪）",
    civilization: "古希腊",
    museum: "卢浮宫，巴黎",
    featured: false,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Victoire_de_Samothrace_-_Musee_du_Louvre_-_20190812.jpg/800px-Victoire_de_Samothrace_-_Musee_du_Louvre_-_20190812.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Victoire_de_Samothrace_-_Musee_du_Louvre_-_20190812.jpg/640px-Victoire_de_Samothrace_-_Musee_du_Louvre_-_20190812.jpg",
    summary: "海风吹进大理石衣褶，无头的女神仍像刚刚降落。",
    story: "胜利女神 Nike 立在船首造型的底座上，衣袂被海风紧贴身体。头与双臂已失，可是迈步与翅膀仍让人听见浪声。它可能为纪念海战而立于萨莫色雷斯岛圣所。今天它停在卢浮宫达卢阶梯上，所有上楼的人都会被那一阵并不存在的风拦住。"
  },
  {
    id: "david",
    name: "大卫像",
    type: "雕塑",
    era: "文艺复兴（1501–1504）",
    civilization: "意大利文艺复兴",
    museum: "学院美术馆，佛罗伦萨",
    featured: true,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/%27David%27_by_Michelangelo_Fir_JBU004.jpg/800px-%27David%27_by_Michelangelo_Fir_JBU004.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/%27David%27_by_Michelangelo_Fir_JBU004.jpg/640px-%27David%27_by_Michelangelo_Fir_JBU004.jpg",
    summary: "投石之前的少年，把紧张写成一种站立的方式。",
    story: "米开朗基罗从一块被弃的大理石中释放出大卫。他没有选择胜利之后的姿态，而是选择对决之前：颈部肌腱绷紧，目光投向远方的歌利亚。佛罗伦萨把这座像视为共和国的象征——弱小者也可以冷静地站着。石头在这里学会了呼吸。"
  },
  {
    id: "nefertiti",
    name: "奈费尔提蒂胸像",
    type: "雕塑",
    era: "古埃及第十八王朝（约公元前 1345 年）",
    civilization: "古埃及",
    museum: "新博物馆，柏林",
    featured: true,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Nofretete_Neues_Museum.jpg/800px-Nofretete_Neues_Museum.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Nofretete_Neues_Museum.jpg/640px-Nofretete_Neues_Museum.jpg",
    summary: "彩色石灰岩做成的王后，侧脸几乎定义了“埃及美”。",
    story: "这尊胸像在阿马尔纳的雕刻作坊被发现，可能是工匠的模型。高冠、修长的颈、未完成的左眼，让它同时像成品与草稿。奈费尔提蒂与阿肯那顿推动对阿顿神的崇拜，城市很快被放弃，胸像却把那十年的审美冻结下来。她看着我们，像在确认自己仍未被时间说服。"
  },
  {
    id: "moai",
    name: "阿胡通加里基摩艾",
    type: "雕塑",
    era: "约 13–16 世纪",
    civilization: "拉帕努伊文明",
    museum: "复活节岛，智利（原址）",
    featured: false,
    image: "https://upload.wikimedia.org/wikipedia/commons/5/50/AhuTongariki.JPG",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/5/50/AhuTongariki.JPG",
    summary: "十五尊祖先像排成一列，目光越过太平洋。",
    story: "摩艾并非神秘的外星人遗物，而是拉帕努伊人雕刻的祖先像。阿胡通加里基是岛上最长的祭坛平台之一，巨像面向聚落，曾戴着红石冠。岛上资源有限，巨像却越来越大——纪念祖先的渴望，有时也会把一座岛推到极限。"
  },
  {
    id: "mona-lisa",
    name: "蒙娜丽莎",
    type: "绘画",
    era: "文艺复兴（约 1503–1519）",
    civilization: "意大利文艺复兴",
    museum: "卢浮宫，巴黎",
    featured: true,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/800px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/500px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg",
    summary: "一层层薄雾般的晕涂，让微笑停在将起未起之处。",
    story: "达·芬奇用 sfumato 把轮廓溶进空气里，丽莎·盖拉尔迪尼的表情因此无法被一次看清。背景的道路与河流像从肩头流走的时间。这幅木板油画后来成为世界上被观看最多的面孔之一，不是因为秘密，而是因为它把“看一个人”这件事，做成了可以反复发生的经验。"
  },
  {
    id: "qingming",
    name: "清明上河图",
    type: "绘画",
    era: "北宋（12 世纪初）",
    civilization: "中华文明 · 宋",
    museum: "故宫博物院，北京",
    featured: true,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Bianjing_city_gate.JPG/1280px-Bianjing_city_gate.JPG",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Bianjing_city_gate.JPG/800px-Bianjing_city_gate.JPG",
    summary: "汴河两岸的清明时节，一座都城在手卷里慢慢展开。",
    story: "张择端把北宋东京画成可以走进去的长卷：城门、骆驼队、虹桥上船夫在喊，店铺在招揽。没有英雄站在画面中央，生活本身就是主题。手卷必须从右向左展开，观看变成一场旅行。后来的摹本无数，但原作仍是中国人对城市最深的记忆之一。"
  },
  {
    id: "great-wave",
    name: "神奈川冲浪里",
    type: "绘画",
    era: "江户时代（约 1831）",
    civilization: "日本",
    museum: "东京国立博物馆等馆藏（多版）",
    featured: true,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Tsunami_by_hokusai_19th_century.jpg/1280px-Tsunami_by_hokusai_19th_century.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Tsunami_by_hokusai_19th_century.jpg/800px-Tsunami_by_hokusai_19th_century.jpg",
    summary: "一排爪形浪尖里，富士山小得像一粒镇定的心。",
    story: "葛饰北斋的这张浮世绘属于《富岳三十六景》。普鲁士蓝让浪壁近乎垂直，三艘渔船被夹在水的缝隙中。远处富士山稳定如印。它本来是可以买回家的版画，后来成为日本视觉的世界名片。浪再高，山仍在——这是一种构图，也是一种脾气。"
  },
  {
    id: "starry-night",
    name: "星夜",
    type: "绘画",
    era: "1889",
    civilization: "荷兰 / 后印象派",
    museum: "现代艺术博物馆，纽约",
    featured: false,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1280px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/800px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg",
    summary: "圣雷米疗养院窗外的夜空，被画成旋转的河流。",
    story: "梵高在普罗旺斯的精神病院里看见这片夜。柏树像火焰，村庄在下面安静地亮着灯，星星被旋成涡流。他写信给弟弟提奥，说夜比白天更有颜色。这幅画后来成为现代艺术的图标，可它最初只是一个失眠的人，试图把天空画得足够大，好把自己放进去。"
  },
  {
    id: "the-kiss",
    name: "吻",
    type: "绘画",
    era: "1907–1908",
    civilization: "维也纳分离派",
    museum: "美景宫，维也纳",
    featured: false,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg/800px-The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg/640px-The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg",
    summary: "金箔把拥抱包成一座小型圣龛。",
    story: "克里姆特用金箔、几何纹和柔软的身体做成这场亲吻。男人的长袍是矩形，女人的是圆形与花朵，两个图案系统在拥抱里相遇。画面边缘是开满花的悬崖。黄金让爱情看起来像仪式，也像危险：灿烂，却站在高处。"
  },
  {
    id: "tutankhamun-mask",
    name: "图坦卡蒙金面具",
    type: "金银器",
    era: "古埃及新王国第十八王朝（约公元前 1323 年）",
    civilization: "古埃及",
    museum: "埃及文明博物馆，开罗",
    featured: true,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/CairoEgMuseumTaaMaskMostlyPhotographed.jpg/800px-CairoEgMuseumTaaMaskMostlyPhotographed.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/CairoEgMuseumTaaMaskMostlyPhotographed.jpg/640px-CairoEgMuseumTaaMaskMostlyPhotographed.jpg",
    summary: "少年法老的殡葬面容，黄金与琉璃蓝组成永恒的皮肤。",
    story: "1922 年卡特打开图坦卡蒙墓时，这张面具仍覆盖在木乃伊头部。黄金锤揲成形，眉、眼线镶玻璃与宝石，胡须编成神的辫纹。墓主只活到十几岁，面具却把他做成不会老的神。黄金在埃及不是奢侈，是让身体配得上太阳的材料。"
  },
  {
    id: "faberge-egg",
    name: "法贝热彩蛋",
    type: "金银器",
    era: "19 世纪末至 20 世纪初",
    civilization: "俄罗斯帝国",
    museum: "克里姆林宫军械库等馆藏",
    featured: false,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Faberg%C3%A9_egg_Rome_05.JPG/1280px-Faberg%C3%A9_egg_Rome_05.JPG",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Faberg%C3%A9_egg_Rome_05.JPG/800px-Faberg%C3%A9_egg_Rome_05.JPG",
    summary: "金壳里藏着机关与微型世界，帝国把惊喜做成工艺。",
    story: "法贝热工坊为罗曼诺夫皇室制作复活节彩蛋：珐琅、宝石、黄金组成可以打开的容器，里面往往藏着肖像、马车或地图。它们是家庭礼物，也是帝国审美的浓缩。革命之后，这些蛋散落世界，成为旧宫廷最闪亮的遗物。"
  },
  {
    id: "liangzhu-cong",
    name: "良渚玉琮王",
    type: "玉石器",
    era: "新石器时代良渚文化（约公元前 3000–2500 年）",
    civilization: "良渚文明",
    museum: "浙江省博物馆，杭州",
    featured: false,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Jade_Cong_King%2C_2018-06-09_01.jpg/1280px-Jade_Cong_King%2C_2018-06-09_01.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Jade_Cong_King%2C_2018-06-09_01.jpg/800px-Jade_Cong_King%2C_2018-06-09_01.jpg",
    summary: "外方内圆的玉管，四面刻着神人兽面，是礼玉的源头之一。",
    story: "琮像一座可以握在手里的宇宙模型：外方象地，内圆象天。良渚人在反山墓地随葬了大量玉器，这件“琮王”体量最大，刻纹最完整。神人与兽面叠在一起，说明长江下游很早就发展出复杂的信仰与权力。玉比青铜更早，成为中国礼制的石头起点。"
  },
  {
    id: "jade-suit",
    name: "金缕玉衣",
    type: "玉石器",
    era: "西汉（公元前 2 世纪）",
    civilization: "中华文明 · 汉",
    museum: "河北博物院，石家庄",
    featured: false,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Xihan_Tomb_1_Jade_Burial_Suit.JPG/1280px-Xihan_Tomb_1_Jade_Burial_Suit.JPG",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Xihan_Tomb_1_Jade_Burial_Suit.JPG/800px-Xihan_Tomb_1_Jade_Burial_Suit.JPG",
    summary: "用金丝把两千多片玉缝成衣服，让诸侯在地下仍保持完整。",
    story: "中山靖王刘胜墓出土的金缕玉衣，以玉片覆盖全身，孔眼穿金缕。汉人相信玉能守魄。这件衣服并没有让身体不朽，却把一种对死亡的谈判保存下来：如果肉身会消失，至少用石头为它做一件不会腐烂的外衣。考古把它从黄土里重新穿好，像把一个旧承诺再读一遍。"
  },
  {
    id: "sun-stone",
    name: "阿兹特克太阳历石",
    type: "玉石器",
    era: "阿兹特克晚期（约 16 世纪初）",
    civilization: "阿兹特克",
    museum: "国立人类学博物馆，墨西哥城",
    featured: false,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Monolito_de_la_Piedra_del_Sol.jpg/1280px-Monolito_de_la_Piedra_del_Sol.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Monolito_de_la_Piedra_del_Sol.jpg/800px-Monolito_de_la_Piedra_del_Sol.jpg",
    summary: "圆形玄武岩上刻着第五太阳的脸，时间被雕成可以凝视的盘。",
    story: "太阳历石中央是太阳神或大地神的面容，四周环绕着以往四个世界毁灭的符号。西班牙征服后，它曾被埋在墨西哥城主教座堂附近，18 世纪重见天日。阿兹特克人相信当前世界是第五太阳，需要祭祀才能继续运转。这块石头把宇宙史压缩成一个圆，让时间有一张脸。"
  },
  {
    id: "rosetta",
    name: "罗塞塔石碑",
    type: "文书碑刻",
    era: "托勒密王朝（公元前 196 年）",
    civilization: "古埃及 / 希腊化世界",
    museum: "大英博物馆，伦敦",
    featured: true,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Rosetta_Stone.JPG/800px-Rosetta_Stone.JPG",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Rosetta_Stone.JPG/640px-Rosetta_Stone.JPG",
    summary: "同一道诏书刻成三种文字，成为打开象形文字的钥匙。",
    story: "石碑用圣书体、世俗体和古希腊文重复同一内容，本是托勒密五世的颂德诏书。1799 年在尼罗河口被发现后，商博良据此释读埃及象形文字。一块行政公文，意外成为现代埃及学的出生证明。语言一旦被重新听懂，整座文明才从沉默里走回来。"
  },
  {
    id: "hammurabi",
    name: "汉谟拉比法典石柱",
    type: "文书碑刻",
    era: "古巴比伦（约公元前 1755 年）",
    civilization: "两河文明",
    museum: "卢浮宫，巴黎",
    featured: false,
    image: "https://upload.wikimedia.org/wikipedia/commons/6/64/P1050763_Louvre_code_Hammurabi_face_rwk.JPG",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/6/64/P1050763_Louvre_code_Hammurabi_face_rwk.JPG",
    summary: "太阳神把权杖交给国王，法律从石头顶端往下生长。",
    story: "玄武岩石柱顶端浮雕：沙玛什端坐，汉谟拉比肃立受法。柱身刻着两百余条判决，涉及贸易、家庭、伤害与奴隶。它并非现代意义上的平等法典，却是把王权写成可被看见的规则。盗碑者曾把它带到苏萨，法国考古队再带到巴黎。法律的旅行，有时比法律本身更长。"
  },
  {
    id: "bayeux",
    name: "巴约挂毯",
    type: "织物",
    era: "11 世纪",
    civilization: "诺曼 / 中世纪欧洲",
    museum: "巴约挂毯博物馆，法国",
    featured: false,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Odo_bayeux_tapestry.png/1280px-Odo_bayeux_tapestry.png",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Odo_bayeux_tapestry.png/800px-Odo_bayeux_tapestry.png",
    summary: "七十余米绣线，把诺曼征服英格兰绣成连续画卷。",
    story: "严格说它是刺绣而非织毯：亚麻底上用羊毛线绣出船只、宴会、彗星和黑斯廷斯战役。图中巴约主教奥多在为战士打气。它可能为奥多而作，从诺曼视角讲述 1066 年。织物比石头更怕潮湿与火，这件能保存下来，几乎是中世纪叙事艺术的奇迹。"
  },
  {
    id: "unicorn-tapestry",
    name: "被俘的独角兽",
    type: "织物",
    era: "约 1495–1505",
    civilization: "中世纪晚期欧洲",
    museum: "修道院博物馆，纽约",
    featured: false,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/The_Unicorn_in_Captivity.jpg/800px-The_Unicorn_in_Captivity.jpg",
    thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/The_Unicorn_in_Captivity.jpg/640px-The_Unicorn_in_Captivity.jpg",
    summary: "独角兽被围在石榴树下的围栏里，千花地上开满象征。",
    story: "《独角兽挂毯》组画里，这一幅常被单独记住：独角兽安坐栅栏中，颈上锁链系着石榴树，背景是密密的千花地。它可能象征爱情被驯服，也可能是基督受难后的宁静。羊毛、丝线与金银线把一座花园织进房间。织物在这里不是软装饰，而是可以悬挂的神学。"
  }
];
